// frontend/src/app/(knowledgebank)/new/organisation/page.tsx
"use client"

import React from 'react';
import { useRouter } from 'next/navigation';
import { toast } from 'sonner';
import { Spinner } from '@/components/ui/spinner';

export default function NewOrganisationPage()
{
    const router = useRouter();
    const [isLoading, setIsLoading] = React.useState(false);
    const [isCheckingDuplicate, setIsCheckingDuplicate] = React.useState(false);
    const [duplicateInfo, setDuplicateInfo] = React.useState<{ exists: boolean; id: string } | null>(null);
    const [formData, setFormData] = React.useState({
        name: '',
        description: '',
        website: '',
        emailAddress: ''
    });

    // Debounce timer ref
    const checkDuplicateTimerRef = React.useRef<NodeJS.Timeout | null>(null);

    const checkForDuplicate = React.useCallback(async (name: string) => {
        if (!name.trim()) {
            setDuplicateInfo(null);
            return;
        }

        setIsCheckingDuplicate(true);
        try {
            const response = await fetch(`/api/organisations/exists?name=${encodeURIComponent(name)}`, {
                credentials: 'include'
            });
            const data = await response.json();

            if (response.ok && data.body) {
                setDuplicateInfo({
                    exists: data.body.exists,
                    id: data.body.id
                });
            }
        } catch (error) {
            console.error('Error checking for duplicate:', error);
        } finally {
            setIsCheckingDuplicate(false);
        }
    }, []);

    const handleInputChange = (field: string, value: string) => {
        setFormData(prev => ({ ...prev, [field]: value }));

        // If name field changed, debounce the duplicate check
        if (field === 'name') {
            // Clear existing timer
            if (checkDuplicateTimerRef.current) {
                clearTimeout(checkDuplicateTimerRef.current);
            }

            // Set new timer
            checkDuplicateTimerRef.current = setTimeout(() => {
                checkForDuplicate(value);
            }, 500); // Wait 500ms after user stops typing
        }
    };

    // Cleanup timer on unmount
    React.useEffect(() => {
        return () => {
            if (checkDuplicateTimerRef.current) {
                clearTimeout(checkDuplicateTimerRef.current);
            }
        };
    }, []);

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();

        // Validate required fields
        if (!formData.name.trim()) {
            toast.error('Name is required');
            return;
        }

        // Check for duplicate
        if (duplicateInfo?.exists) {
            toast.error('An organisation with this name already exists. Please use a different name or view the existing organisation.');
            return;
        }

        setIsLoading(true);

        try {
            const response = await fetch('/api/organisations/new', {
                method: 'PUT',
                headers: {
                    'Content-Type': 'application/json',
                },
                credentials: 'include',
                body: JSON.stringify({
                    Name: formData.name,
                    Description: formData.description || undefined,
                    Website: formData.website || undefined,
                    EmailAddress: formData.emailAddress || undefined,
                    OrganisationRelations: []
                }),
            });

            const responseData = await response.json();

            if (!response.ok) {
                throw new Error(responseData.message || 'Failed to create organisation');
            }

            toast.success('Organisation created successfully!');
            console.log('Organisation ID:', responseData.body);

            // Navigate to the archive with the new organisation selected
            router.push(`/archive?id=${responseData.body}`);

        } catch (error) {
            console.error('Error creating organisation:', error);
            toast.error(`Error creating organisation: ${error instanceof Error ? error.message : 'Unknown error'}`);
        } finally {
            setIsLoading(false);
        }
    };

    const canSubmit = formData.name.trim().length > 0 && !isLoading && !duplicateInfo?.exists;

    return (
        <div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-3xl py-10">
            <div className="w-full text-center mb-8">
                <h1 className="text-3xl font-semibold text-gray-900 mb-2">
                    Create a New Organisation
                </h1>
                <p className="text-sm text-gray-600">
                    Add a new organisation to your knowledge base
                </p>
            </div>

            <form onSubmit={handleSubmit} className="space-y-6">
                {/* Basic Information */}
                <div className="bg-white border border-gray-300 rounded-lg p-6">
                    <h2 className="text-lg font-semibold text-gray-900 mb-4 border-b border-gray-200 pb-2">
                        Basic Information
                    </h2>
                    <div className="space-y-4">
                        {/* Name */}
                        <div>
                            <label htmlFor="name" className="block text-sm font-medium text-gray-700 mb-1">
                                Name <span className="text-red-500">*</span>
                            </label>
                            <input
                                type="text"
                                id="name"
                                value={formData.name}
                                onChange={(e) => handleInputChange('name', e.target.value)}
                                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 focus:border-transparent ${
                                    duplicateInfo?.exists
                                        ? 'border-red-300 focus:ring-red-500'
                                        : 'border-gray-300 focus:ring-purple-500'
                                }`}
                                placeholder="Enter organisation name"
                                required
                            />
                            {isCheckingDuplicate && (
                                <p className="text-xs text-gray-500 mt-1 flex items-center gap-1">
                                    <Spinner className="w-3 h-3" />
                                    Checking for duplicates...
                                </p>
                            )}
                            {duplicateInfo?.exists && (
                                <div className="mt-2 p-3 bg-red-50 border border-red-200 rounded-md">
                                    <p className="text-sm text-red-800 font-medium mb-2">
                                        An organisation with this name already exists
                                    </p>
                                    <button
                                        type="button"
                                        onClick={() => router.push(`/archive?id=${duplicateInfo.id}`)}
                                        className="text-sm text-red-700 underline hover:text-red-900"
                                    >
                                        View existing organisation
                                    </button>
                                </div>
                            )}
                        </div>

                        {/* Description */}
                        <div>
                            <label htmlFor="description" className="block text-sm font-medium text-gray-700 mb-1">
                                Description
                            </label>
                            <textarea
                                id="description"
                                value={formData.description}
                                onChange={(e) => handleInputChange('description', e.target.value)}
                                rows={4}
                                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent resize-none"
                                placeholder="Brief description of the organisation"
                            />
                        </div>
                    </div>
                </div>

                {/* Contact Information */}
                <div className="bg-white border border-gray-300 rounded-lg p-6">
                    <h2 className="text-lg font-semibold text-gray-900 mb-4 border-b border-gray-200 pb-2">
                        Contact Information
                    </h2>
                    <div className="space-y-4">
                        {/* Website */}
                        <div>
                            <label htmlFor="website" className="block text-sm font-medium text-gray-700 mb-1">
                                Website
                            </label>
                            <input
                                type="url"
                                id="website"
                                value={formData.website}
                                onChange={(e) => handleInputChange('website', e.target.value)}
                                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                                placeholder="https://example.com"
                            />
                        </div>

                        {/* Email */}
                        <div>
                            <label htmlFor="emailAddress" className="block text-sm font-medium text-gray-700 mb-1">
                                Email Address
                            </label>
                            <input
                                type="email"
                                id="emailAddress"
                                value={formData.emailAddress}
                                onChange={(e) => handleInputChange('emailAddress', e.target.value)}
                                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                                placeholder="contact@example.com"
                            />
                        </div>
                    </div>
                </div>

                {/* Action Buttons */}
                <div className="flex justify-center gap-4 pt-4">
                    <button
                        type="button"
                        onClick={() => router.back()}
                        disabled={isLoading}
                        className="px-8 py-3 border-2 border-gray-300 text-gray-700 rounded-lg font-semibold
                        hover:bg-gray-50 transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                        Cancel
                    </button>
                    <button
                        type="submit"
                        disabled={!canSubmit}
                        className="px-8 py-3 bg-purple-600 text-white rounded-lg font-semibold
                        hover:bg-purple-700 transition-all hover:shadow-lg hover:-translate-y-0.5
                        disabled:bg-gray-300 disabled:cursor-not-allowed disabled:transform-none disabled:shadow-none
                        flex items-center gap-2"
                    >
                        {isLoading && <Spinner className="w-4 h-4" />}
                        {isLoading ? 'Creating...' : 'Create Organisation'}
                    </button>
                </div>
            </form>
        </div>
    );
}

// frontend-svelte/src/routes/(app)/new/organisation/+page.svelte
<script lang="ts">
    import { goto } from '$app/navigation';
    import { debounce } from '$lib/utils/debounce';
    import { api } from '$lib/api';
    import Input from '$lib/components/ui/input/input.svelte';
    import Button from '$lib/components/ui/button/button.svelte';
    import Textarea from '$lib/components/ui/textarea/textarea.svelte';
    import Label from '$lib/components/ui/label/label.svelte';
    import { toast } from 'svelte-sonner';

    let name = $state('');
    let description = $state('');
    let email = $state('');
    let website = $state('');

    let isSubmitting = $state(false);
    let isCheckingDuplicate = $state(false);
    let duplicate = $state<{ exists: boolean; id: string; } | null>(null);
    let similar = $state<{ id: string; name: string; }[]>([]);

    const debouncedCheckDuplicate = debounce(checkDuplicate, 500);

    function onNameInput() {
        duplicate = null;
        similar = [];
        if (!name.trim()) return;
        debouncedCheckDuplicate();
    }

    async function checkDuplicate() {
        isCheckingDuplicate = true;

        try {
            const result = await api.get<{ exists: boolean; id: string; }>(`/api/organisations/exists?name=${encodeURIComponent(name)}`);
            duplicate = result.body;

            const listResult = await api.get<{ id: string; name: string; }[]>(`/api/organisations/list?searchQuery=${encodeURIComponent(name)}&pageSize=3&properties=Id,Name`);
            similar = listResult.body.filter(o => o.name.toLowerCase() !== name.toLowerCase());
        } catch {
            // Silently ignore
        } finally {
            isCheckingDuplicate = false;
        }
    }

    async function handleSubmit(e: SubmitEvent) {
        e.preventDefault();

        if (!name.trim()) return;

        isSubmitting = true;
        try {
            const result = await api.put<string>('/api/organisations/new', {
                Name: name,
                Description: description || undefined,
                EmailAddress: email || undefined,
                Website: website || undefined
            });

            goto(`/library?inspectorId=${result.body}&inspectorType=organisation`);
        } catch (e) {
            toast.error(e instanceof Error ? e.message : 'Failed to create organisation');
        } finally {
            isSubmitting = false;
        }
    }

    const canSubmit = $derived(name.trim().length > 0 && !isSubmitting && !duplicate?.exists);
</script>

<div class="mx-auto flex max-w-2xl flex-col gap-6 p-8 h-full justify-center">
    <!-- Header -->
    <div>
        <h1 class="text-2xl font-semibold">Add Organisation</h1>
        <p class="text-muted-foreground mt-1 text-sm">Add a new organisation to the library.</p>
    </div>

    <!-- Form -->
    <form onsubmit={handleSubmit} class="flex flex-col gap-6">
        <!-- Card -->
        <div class="border-border flex flex-col gap-4 rounded-lg border p-6">
            <!-- Name (Required) -->
            <div class="flex flex-col gap-1.5">
                <Label for="name">Name <span class="text-destructive">*</span></Label>
                <Input id="name" bind:value={name} oninput={onNameInput} placeholder="Organisation name" />
                {#if isCheckingDuplicate}
                    <p class="text-muted-foreground text-xs">Checking for duplicates...</p>
                {:else if duplicate?.exists}
                    <p class="text-destructive text-xs">
                        An organisation with this name already exists.
                        <a href="/library?inspectorId={duplicate.id}&inspectorType=organisation" class="underline">View</a>
                    </p>
                {:else if similar.length > 0}
                    <p class="text-muted-foreground text-xs">
                        Similar names in the library:
                        {#each similar as s, i (s.id)}
                            <a href="/library?inspectorId={s.id}&inspectorType=organisation" class="underline">{s.name}</a>{#if i < similar.length - 1},&nbsp;{/if}
                        {/each}
                    </p>
                {/if}
            </div>

            <!-- Email -->
            <div class="flex flex-col gap-1.5">
                <Label for="email">Email</Label>
                <Input id="email" type="email" bind:value={email} placeholder="contact@example.com" />
            </div>

            <!-- Website -->
            <div class="flex flex-col gap-1.5">
                <Label for="website">Website</Label>
                <Input id="website" type="url" bind:value={website} placeholder="https://example.com" />
            </div>

            <!-- Description -->
            <div class="flex flex-col gap-1.5">
                <Label for="description">Description</Label>
                <Textarea id="description" bind:value={description} placeholder="Brief description of the organisation" rows={4} />
            </div>
        </div>


        <!-- Actions -->
        <div class="flex justify-end gap-3">
            <Button variant="outline" type="button" onclick={() => history.back()}>Cancel</Button>
            <Button type="submit" disabled={!canSubmit}>
                {isSubmitting ? 'Creating...' : 'Create Organisation'}
            </Button>
        </div>
    </form>
</div>
