// frontend/src/components/sidebars/archive-sidebar/EditableDate.tsx
"use client"

import React, { JSX } from 'react';
import { Input } from "@/components/ui/input";
import { format, parseISO } from 'date-fns';

// Helper to normalize precision (handle both string and numeric enum values)
const normalizePrecision = (precision?: 'Year' | 'Month' | 'Day' | number | null): 'Year' | 'Month' | 'Day' => {
    if (precision === 0 || precision === 'Year') return 'Year';
    if (precision === 1 || precision === 'Month') return 'Month';
    if (precision === 2 || precision === 'Day') return 'Day';
    return 'Day'; // default
};

interface EditableDateProps {
    date: Date | null;
    text: string;
    icon: JSX.Element;
    cName: string;
    editMode: boolean;
    precision?: 'Year' | 'Month' | 'Day' | number | null;
    onDateChange?: (date: Date | null) => void;
    onPrecisionChange?: (precision: 'Year' | 'Month' | 'Day') => void;
}

export default function EditableDate({
    date,
    text,
    icon,
    cName,
    editMode,
    precision,
    onDateChange,
    onPrecisionChange
}: EditableDateProps) {
    const normalizedPrecision = normalizePrecision(precision);
    const [localPrecision, setLocalPrecision] = React.useState(normalizedPrecision);

    React.useEffect(() => {
        setLocalPrecision(normalizedPrecision);
    }, [normalizedPrecision]);

    const handlePrecisionChange = (newPrecision: 'Year' | 'Month' | 'Day') => {
        setLocalPrecision(newPrecision);
        if (onPrecisionChange) {
            onPrecisionChange(newPrecision);
        }
    };

    const formatDate = (date: Date | null, datePrecision: 'Year' | 'Month' | 'Day') => {
        if (!date) return '';
        const d = new Date(date);

        if (datePrecision === 'Year') {
            return d.getFullYear().toString();
        } else if (datePrecision === 'Month') {
            return format(d, 'MMMM yyyy');
        } else {
            return format(d, 'MMM d, yyyy');
        }
    };

    const handleDateChange = (e: React.ChangeEvent<HTMLInputElement> | { target: { value: string } }) => {
        const newValue = e.target.value;
        if (newValue && onDateChange) {
            try {
                // Parse the date from the input (YYYY-MM-DD format)
                const parsedDate = parseISO(newValue);
                onDateChange(parsedDate);
            } catch (error) {
                console.error('Invalid date format:', error);
            }
        } else if (!newValue && onDateChange) {
            // If the date is cleared, set it to null
            onDateChange(null);
        }
    };

    const handleYearChange = (e: React.ChangeEvent<HTMLInputElement>) => {
        const year = e.target.value;
        if (year && onDateChange) {
            handleDateChange({ target: { value: `${year}-01-01` } });
        }
    };

    const handleMonthChange = (month: string, year: string) => {
        if (month && year && onDateChange) {
            handleDateChange({ target: { value: `${year}-${month}-01` } });
        }
    };

    const getInputValue = () => {
        if (!date) return '';
        try {
            // Format date to YYYY-MM-DD for the input field
            return format(new Date(date), 'yyyy-MM-dd');
        } catch {
            return '';
        }
    };

    if (editMode) {
        return (
            <div className="flex flex-col gap-2 min-w-0">
                <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                        {icon}
                        <span className="text-gray-700 text-sm">{text}</span>
                    </div>
                    <div className="flex gap-1 text-xs">
                        <button
                            type="button"
                            onClick={() => handlePrecisionChange('Year')}
                            className={`px-2 py-1 rounded ${
                                localPrecision === 'Year'
                                    ? 'bg-purple-600 text-white'
                                    : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
                            }`}
                        >
                            Year
                        </button>
                        <button
                            type="button"
                            onClick={() => handlePrecisionChange('Month')}
                            className={`px-2 py-1 rounded ${
                                localPrecision === 'Month'
                                    ? 'bg-purple-600 text-white'
                                    : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
                            }`}
                        >
                            Month
                        </button>
                        <button
                            type="button"
                            onClick={() => handlePrecisionChange('Day')}
                            className={`px-2 py-1 rounded ${
                                localPrecision === 'Day'
                                    ? 'bg-purple-600 text-white'
                                    : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
                            }`}
                        >
                            Day
                        </button>
                    </div>
                </div>
                <div className="flex flex-col min-w-0">
                    {localPrecision === 'Year' ? (
                        <Input
                            type="number"
                            value={date ? new Date(date).getFullYear() : ''}
                            onChange={handleYearChange}
                            min="1900"
                            max="2100"
                            placeholder="YYYY"
                            className="h-8 text-sm font-medium"
                        />
                    ) : localPrecision === 'Month' ? (
                        <div className="flex gap-2">
                            <select
                                value={date ? String(new Date(date).getMonth() + 1).padStart(2, '0') : '01'}
                                onChange={(e) => {
                                    const year = date ? String(new Date(date).getFullYear()) : String(new Date().getFullYear());
                                    handleMonthChange(e.target.value, year);
                                }}
                                className="flex-1 h-8 text-sm font-medium px-2 border rounded"
                            >
                                <option value="01">January</option>
                                <option value="02">February</option>
                                <option value="03">March</option>
                                <option value="04">April</option>
                                <option value="05">May</option>
                                <option value="06">June</option>
                                <option value="07">July</option>
                                <option value="08">August</option>
                                <option value="09">September</option>
                                <option value="10">October</option>
                                <option value="11">November</option>
                                <option value="12">December</option>
                            </select>
                            <Input
                                type="number"
                                value={date ? new Date(date).getFullYear() : ''}
                                onChange={(e) => {
                                    const month = date ? String(new Date(date).getMonth() + 1).padStart(2, '0') : '01';
                                    handleMonthChange(month, e.target.value);
                                }}
                                min="1900"
                                max="2100"
                                placeholder="YYYY"
                                className="w-24 h-8 text-sm font-medium"
                            />
                        </div>
                    ) : (
                        <Input
                            type="date"
                            value={getInputValue()}
                            onChange={handleDateChange}
                            className="h-8 text-sm font-medium"
                        />
                    )}
                </div>
            </div>
        );
    }

    return (
        <div className={cName}>
            {icon}
            <div className="truncate">
                <span className="text-gray-700">{text}</span>
                <div className="font-medium text-gray-700">
                    {formatDate(date, normalizedPrecision)}
                </div>
            </div>
        </div>
    );
}

// This program has been developed by students from the bachelor Computer Science at Utrecht
// University within the Software Project course.
// © Copyright Utrecht University (Department of Information and Computing Sciences)

// frontend-svelte/src/lib/components/inspector/editable-date.svelte
<script lang="ts">
    import { getContext, untrack } from 'svelte';
    import type { DatePrecision } from '$lib/types/resource';
    import { formatDate } from '$lib/utils/date';

    let { date, precision, onsave }: {
        date?: string;
        precision?: DatePrecision;
        onsave: (date: string | null, precision: DatePrecision) => Promise<void>;
    } = $props();

    const getEditMode = getContext<() => boolean>('getEditMode');
    let editMode = $derived(getEditMode());
    const registerSave = getContext<(p: Promise<void>) => void>('registerSave');

    let localPrecision = $state<DatePrecision>(untrack(() => precision ?? 'Day'));
    let inputState = $state(untrack(() => getInputStr()));

    function getInputStr(): string {
        if (!date) return '';
        const d = new Date(date);
        if (localPrecision === 'Year') return String(d.getFullYear());
        if (localPrecision === 'Month') return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`;
        return date.split('T')[0];
    }

    function toIsoDate(val: string, prec: DatePrecision): string | null {
        if (!val) return null;
        if (prec === 'Year') return `${val}-01-01`;
        if (prec === 'Month') return `${val}-01`;
        return val;
    }

    function setPrecision(p: DatePrecision) {
        localPrecision = p;
        inputState = getInputStr();
        registerSave?.(onsave(toIsoDate(inputState, p), p));
    }

    function handleBlur() {
        registerSave?.(onsave(toIsoDate(inputState, localPrecision), localPrecision));
    }
</script>

{#if editMode}
    <div class="flex flex-col gap-1.5">
        <div class="flex items-center gap-1">
            <span class="mr-1">Published</span>
            {#each (['Year', 'Month', 'Day'] as DatePrecision[]) as p}
                <button
                    onclick={() => setPrecision(p)}
                    class="px-1.5 py-0.5 rounded {localPrecision === p ? 'bg-primary text-primary-foreground' : 'bg-muted hover:bg-muted/80'}"
                >
                    {p}
                </button>
            {/each}
            {#if inputState}
                <button
                    onclick={() => { inputState = ''; registerSave?.(onsave(null, localPrecision)); }}
                    class="px-1.5 py-0.5 rounded text-destructive hover:bg-destructive/10 ml-auto"
                >
                    Clear
                </button>
            {/if}
        </div>
        {#if localPrecision === 'Year'}
            <input
                type="number"
                bind:value={inputState}
                onblur={handleBlur}
                min="1900" max="2100"
                placeholder="YYYY"
                class="bg-transparent border-b border-input focus:outline-none focus:border-ring py-0.5 w-20"
            />
        {:else if localPrecision === 'Month'}
            <div class="flex gap-2">
                <select
                    value={inputState.split('-')[1] ?? '01'}
                    onchange={(e) => {
                        const year = inputState.split('-')[0] || String(new Date().getFullYear());
                        inputState = `${year}-${(e.target as HTMLSelectElement).value}`;
                        handleBlur();
                    }}
                    class="bg-transparent border-b border-input focus:outline-none focus:border-ring py-0.5"
                >
                    <option value="">Month</option>
                    {#each [['01','January'],['02','February'],['03','March'],['04','April'],['05','May'],['06','June'],['07','July'],['08','August'],['09','September'],['10','October'],['11','November'],['12','December']] as [val, label]}
                        <option value={val}>{label}</option>
                    {/each}
                </select>
                <input
                    type="number"
                    value={inputState.split('-')[0] ?? ''}
                    onblur={(e) => {
                        const month = inputState.split('-')[1] || '01';
                        inputState = `${(e.target as HTMLInputElement).value}-${month}`;
                        handleBlur();
                    }}
                    min="1900" max="2100"
                    placeholder="YYYY"
                    class="bg-transparent border-b border-input focus:outline-none focus:border-ring py-0.5 w-16"
                />
            </div>
        {:else}
            <input
                type="date"
                bind:value={inputState}
                onblur={handleBlur}
                class="bg-transparent border-b border-input focus:outline-none focus:border-ring py-0.5"
            />
        {/if}
    </div>
{:else}
    <span>Published: {formatDate(date ?? '', precision) ?? '-'}</span>
{/if}
