// frontend-svelte/src/routes/(auth)/signup/+page.svelte
<script lang="ts">
    import Input from "$lib/components/ui/input/input.svelte";
    import Button from "$lib/components/ui/button/button.svelte";
    import { goto } from "$app/navigation";
    import { page } from "$app/state";
	import { api } from "$lib/api";
	import { Pencil } from "lucide-svelte";
    
    const token = page.url.searchParams.get('token');
    
    let firstName = $state('');
    let lastName = $state('');
    let email = $state('');
    let password = $state('');
    let passwordRepeat = $state('');
    
    let avatarInputElement: HTMLInputElement | null = $state(null);
    let avatarFile: File | null = $state(null);
    let avatarPreviewUrl = $derived(avatarFile ? URL.createObjectURL(avatarFile) : '/img/default-profile-picture.svg');
    
    let loading = $state(false);
    let error = $state();
    
    async function handleSubmit(e: SubmitEvent) 
    {
        // Prevent default page reload
        e.preventDefault();
        
        if (password != passwordRepeat) 
        {
            error = 'Passwords don\'t match';
            return;
        }
        
        loading = true;
        error = '';
        
        try 
        {
            // Sign up on backend
            const formData = new FormData();
            
            formData.append('firstName', firstName);
            formData.append('lastName', lastName);
            formData.append('email', email);
            formData.append('password', password);
            formData.append('token', token ?? '');
            
            if (avatarFile)
                formData.append('avatar', avatarFile);
                
            const signupResponse = await api.form('/api/auth/signup', formData);
            
            if (!signupResponse.success) 
            {
                error = signupResponse.message;
                return;
            }
            
            // Log in on backend
            const loginResponse = await fetch('/api/auth/login?useCookies=true&useSessionCookies=true', 
            {
                method: 'POST',
                headers: { 'Content-Type': "application/json" },
                body: JSON.stringify({ email, password })
            });
            
            goto(loginResponse.ok ? '/' : '/login');
        }
        catch 
        {
            error = 'Something went wrong, please try again';
        }
        finally 
        {
            loading = false;
        }
    }
</script>

<div class="mx-auto w-3/4 p-4">
    <form class="flex flex-col gap-4" onsubmit={handleSubmit}>
    
        <div class="flex flex-col gap-1">
            <h1 class="text-3xl font-bold">Sign up</h1>
            <p>Welcome! We're happy to have you.</p>
        </div>
        
        <!-- Avatar + Name -->
        <div class="flex gap-10">
            <!-- Avatar -->
            <div class="flex w-1/3 flex-col gap-1 justify-center items-center">
                <button type="button" onclick={() => avatarInputElement?.click()} class="m-0 p-0 w-35 h-35 bg-transparent border-none group relative cursor-pointer">
                    <img
                        src={avatarPreviewUrl}
                        alt="Avatar preview"
                        class="avatar w-full h-full rounded-full object-cover"
                    />
                    <div class="absolute inset-0 flex items-center justify-center rounded-full opacity-0 group-hover:opacity-100 transition-opacity bg-black/30">
                        <Pencil class="text-white" size={20} />
                    </div>
                </button>
                <input
                    type="file"
                    accept="image/png,image/jpeg,image/webp"
                    bind:this={avatarInputElement}
                    onchange={(e) => (avatarFile = e.currentTarget.files?.[0] ?? null)}
                    hidden
                />
            </div>
            
            <!-- Name fields -->
            <div class="flex flex-1 flex-col gap-1">
                <div class="flex flex-1 flex-col gap-1">
                    <label for="firstName" class="font-bold">First Name</label>
                    <Input bind:value={firstName} type="text" id="firstName" required />
                </div>
                
                <div class="flex flex-1 flex-col gap-1">
                    <label for="lastName" class="font-bold">Last Name</label>
                    <Input bind:value={lastName} type="text" id="lastName" required />
                </div>
            </div>
        </div>
        
        <!-- Email -->
        <div class="flex flex-col gap-1">
            <label for="email" class="font-bold">Email</label>
            <Input bind:value={email} type="email" name="email" id="email" required />
        </div>
        
        <!-- Password -->
        <div class="flex flex-col gap-1">
            <label for="password" class="font-bold">Password</label>
            <Input bind:value={password} type="password" name="password" id="password" required />
        </div>
        
        <div class="flex flex-col gap-1">
            <label for="passwordRepeat" class="font-bold">Repeat Password</label>
            <Input bind:value={passwordRepeat} type="password" name="passwordRepeat" id="passwordRepeat" required />
        </div>
        
        <Button type="submit" class="w-full" disabled={!firstName || !lastName || !email || !password || !passwordRepeat || loading}>
            {#if loading}
                Signing up...
            {:else}
                Sign up
            {/if}
        </Button>
        
        {#if error}
            <p class="pl-2 text-sm text-destructive">{error}</p>
        {/if}
        
        <p class="text-center text-muted-foreground">Already have an account? <a href='/login' class="text-blue-500">Log in</a>.</p>
    
    </form>
</div>

// frontend/src/app/(auth)/signup/page.tsx
"use client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Register } from "@/actions/authActions";
import { useState, useActionState, useEffect, startTransition } from "react";
import { toast } from "sonner";
import { FormResponse } from "@/types/return.type";
import { RegisterRequest } from "@/types/registerRequest.type";
import { useRouter } from "next/navigation";
import EditableAvatar from "@/components/ui/editable-avatar";

const initialState: FormResponse<RegisterRequest> = {
  success: false,
  message: "",
};

type AvatarState = { url: string; blob: Blob | null };

export default function SignUpPage() {
  const [firstName, setFirstName] = useState<string>("");
  const [lastName, setLastName] = useState<string>("");
  const [email, setEmail] = useState<string>("");
  const [password, setPassword] = useState<string>("");
  const [retypePassword, setRetypePassword] = useState<string>("");
  const [avatar, setAvatar] = useState<AvatarState>({ url: "/img/default-profile-picture.svg", blob: null });
  const [termsBox, setTermsBox] = useState<boolean>(false);

  const [state, action, isPending] = useActionState(Register, initialState);

  const router = useRouter();

  const revokeBlobUrl = () => {
    if (avatar.blob) URL.revokeObjectURL(avatar.url);
  };

  // Make sure that the avatars last url is revoked once the component unmounts.
  useEffect(() => {
    return revokeBlobUrl;
  }, []);

  useEffect(() => {
    if (state.success) {
      toast.success(state.message);
      router.push("/login");
      router.refresh();
    } else if (state.message) {
      toast.error(state.message);
    }
  }, [state]);

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);

    if (avatar.blob) formData.append("avatar", avatar.blob);

    startTransition(() => {
      action(formData);
    });
  };

  const handleChange = (blob: Blob | null) => {
    revokeBlobUrl();
    setAvatar({ url: blob ? URL.createObjectURL(blob) : "/img/default-profile-picture.svg", blob });
  };

  return (
    <div className="flex h-full w-full">
      {/* Form */}
      <div className="flex h-full w-full items-center justify-center">
        <div className="mx-auto w-3/4 p-4">
          <form className="flex flex-col gap-6" onSubmit={handleSubmit}>
            <div>
              <h1 className="mb-1 text-3xl font-bold">Sign up</h1>
              <p>Enter your personal data to create your account.</p>
            </div>
            
            {/* Avatar section - full width */}
            <div className="flex w-full justify-center">
              <EditableAvatar url={avatar.url} onConfirm={handleChange} onDefault={() => handleChange(null)} />
            </div>
            
            {/* Name fields section */}
            <div className="flex w-full gap-5">
              <div className="w-full">
                <label htmlFor="firstname" className="font-bold">
                  FIRST NAME
                </label>
                <Input value={firstName} type="text" placeholder="First name" name="firstname" onChange={(e) => setFirstName(e.target.value)} required />
              </div>
              <div className="w-full">
                <label htmlFor="lastname" className="font-bold">
                  LAST NAME
                </label>
                <Input value={lastName} type="text" placeholder="Last name" name="lastname" onChange={(e) => setLastName(e.target.value)} required />
              </div>
            </div>
            
            <div>
              <label htmlFor="email" className="font-bold">
                EMAIL
              </label>
              <Input value={email} type="email" placeholder="Email" name="email" onChange={(e) => setEmail(e.target.value.trim())} required />
            </div>
            <div>
              <label htmlFor="password" className="font-bold">
                PASSWORD
              </label>
              <Input value={password} type="password" placeholder="Password" name="password" onChange={(e) => setPassword(e.target.value)} required />
            </div>
            
            <div>
              <label htmlFor="passwordcheck" className="font-bold">
                RETYPE PASSWORD
              </label>
              <Input value={retypePassword} type="password" placeholder="Password" name="passwordcheck" onChange={(e) => setRetypePassword(e.target.value)} required />
              <div className="flex gap-2">
                <input defaultChecked={termsBox} type="checkbox" name="terms" onChange={(e) => setTermsBox(e.target.checked)} required />
                <label htmlFor="terms" className="text-sm">
                  I agree to the{" "}
                  <a href="termsandconditions" className="text-blue-600 underline hover:text-blue-800">
                    terms and conditions
                  </a>
                  .
                </label>
              </div>
            </div>
            
            <Button
              type="submit"
              className="w-full"
              disabled={firstName.trim() == "" || lastName.trim() == "" || email == "" || password == "" || retypePassword == "" || !termsBox || isPending || state.success}
            >
              {isPending || state.success ? "Signing up..." : "Sign up"}
            </Button>
          </form>
        </div>
      </div>
    </div>
  );
}
