// frontend/src/routes/(auth)/login/+page.svelte
<script lang="ts">
    import Input from "$lib/components/ui/input/input.svelte";
    import Button from "$lib/components/ui/button/button.svelte";
	import { goto } from "$app/navigation";
	import { page } from "$app/state";
    import { toast } from "svelte-sonner";

    const redirect = page.url.searchParams.get('redirect');

    let email = $state('');
    let password = $state('');
    let loading = $state(false);
    
    async function handleSubmit(e: SubmitEvent) 
    {
        // Prevent default page reload
        e.preventDefault();
    
        loading = true;
    
        try 
        {
            // Log in on backend
            const response = await fetch('/api/auth/login?useCookies=true&useSessionCookies=true', 
            {
                method: 'POST',
                headers: { 'Content-Type': "application/json" },
                body: JSON.stringify({ email, password })
            });
            
            if (response.ok) 
            {
                goto(redirect ?? '/');
                return;
            }
            
            password = '';
            toast.error("Incorrect credentials.")
        }
        catch (e)
        {
            toast.error(e instanceof Error ? e.message : "Something went wrong, try again.");
        }
        finally 
        {
            loading = false;
        }
    }
</script>

<!-- Form -->
<div class="w-full max-w-lg px-8 py-4">
    <form class="flex flex-col gap-4" onsubmit={handleSubmit}>
        
        <div class="flex flex-col gap-1">
            <h1 class="text-3xl font-bold">Sign in</h1>
            <p>Welcome back!</p>
        </div>
        
        <div class="flex flex-col gap-1">
            <label for="email" class="font-bold">Email</label>
            <Input bind:value={email} type="email" name="email" id="email" required />
        </div>
        
        <div class="flex flex-col gap-1">
            <label for="password" class="font-bold">Password</label>
            <Input bind:value={password} type="password" name="password" id="password" required />
        </div>
        
        <Button type="submit" class="w-full cursor-pointer" disabled={!email || !password || loading}>
            {#if loading}
                Signing in...
            {:else}
                Sign in
            {/if}
        </Button>
    </form>
</div>

// frontend/src/app/(auth)/login/page.tsx
"use client";

import { Login } from "@/actions/authActions";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { LoginRequest } from "@/types/loginRequest.type";
import { FormResponse } from "@/types/return.type";
import { useRouter } from "next/navigation";
import { useState, useActionState, useEffect } from "react";
import { toast } from "sonner";

const initialState: FormResponse<LoginRequest> = {
    success: false,
    message: "",
  };

export default function LoginPage() {
    const [email, setEmail] = useState<string>("");
    const [password, setPassword] = useState<string>("");
    
    const [state, action, isPending] = useActionState(Login, initialState);
    console.log("Login state:");
    console.log(state.message);
    
    const router = useRouter();
    useEffect(() => {
        if (state.success) {
          toast.success(state.message);
          router.push("/");
        } else if (state.message) {
          toast.error(state.message);
        }
      }, [state]);

    return (
        <div className="flex w-full h-full">
            {/* Form */}
            <div className="flex justify-center items-center h-full w-full">
                <div className="w-3/4 mx-auto p-4">
                    <form className="flex flex-col gap-6" action={action}>
                        <div>
                            <h1 className="font-bold text-3xl mb-1">Sign in</h1>
                            <p>Welcome back, please enter your details to sign in.</p>
                        </div>
                        <div>
                            <label htmlFor="email" className="font-bold">EMAIL</label>
                            <Input value={email} type="text" placeholder="Email" name="email" onChange={(e) => setEmail(e.target.value.trim())} required/>
                        </div>
                        <div>
                            <label htmlFor="password" className="font-bold">PASSWORD</label>
                            <Input value={password} type="password" placeholder="Password" name="password" onChange={(e) => setPassword(e.target.value.trim())} required/>
                        </div>
                        <Button type="submit" className="w-full" disabled={password == "" || email == "" || state.success || isPending}>{isPending || state.success ? "Signing in..." : "Sign in"}</Button>
                    </form>
                </div>
            </div>
        </div>
        
    );
  }
